In [1]:
import pandas as pd
import numpy as np
import matplotlib.pylab as plt
import seaborn as sns

In [2]:
from sklearn.datasets import make_classification    

In [4]:
#create dataset
x,y = make_classification(n_samples=1000,n_features=10,n_classes=2,random_state=2)

In [5]:
pd.DataFrame(x,y)

,0,1,2,3,4,5,6,7,8,9
1,-3.102421,-0.073423,0.419729,0.966164,-0.249183,-0.604993,0.349701,-2.211315,-1.723576,2.271263
1,-0.549656,-0.664368,-1.600997,-1.190788,-0.014673,0.364480,0.215202,-1.206919,0.817516,1.306936
0,-0.932998,-0.298506,2.618170,1.676280,0.670463,-0.147403,-0.188378,1.786321,0.631064,-1.574509
0,-0.932334,0.296483,1.724991,-1.473014,-0.279677,0.450938,-0.121832,0.363662,-0.830501,-0.551381
1,0.727230,2.352253,-0.750424,0.696912,-0.092723,-1.319113,-0.109217,0.501352,-2.375225,-0.597711
...,...,...,...,...,...,...,...,...,...,...
1,0.066982,0.376067,0.396182,-0.395659,-0.328421,1.422595,0.042587,-0.600108,1.450708,0.471718
0,0.482403,-0.284857,-2.586102,-0.853547,1.356690,-0.432839,-0.035363,1.701331,-0.439581,-1.101269
0,-0.841925,0.244521,-0.537821,-0.802820,-0.914685,-0.493491,-0.159474,-0.132825,-0.344576,-0.362626
0,1.425246,-2.398822,0.634409,1.049249,-3.107336,0.912787,-0.737665,0.632652,1.117942,-2.412913


In [6]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [7]:
regression = LogisticRegression()

In [8]:
regression.fit(x_train,y_train)

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,100
,multi_class,'deprecated'


In [10]:
y_pred = regression.predict(x_test)
y_pred

array([0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 0])

In [11]:
print(regression.predict_proba(x_test))

[[8.16948011e-01 1.83051989e-01]
 [3.30974120e-01 6.69025880e-01]
 [4.99126550e-02 9.50087345e-01]
 [9.73984269e-01 2.60157308e-02]
 [1.73287382e-02 9.82671262e-01]
 [6.56223013e-01 3.43776987e-01]
 [8.71443695e-01 1.28556305e-01]
 [4.52641268e-01 5.47358732e-01]
 [1.61816024e-01 8.38183976e-01]
 [9.59489014e-01 4.05109858e-02]
 [1.83006469e-03 9.98169935e-01]
 [9.27423969e-01 7.25760313e-02]
 [3.95844228e-01 6.04155772e-01]
 [5.60510652e-01 4.39489348e-01]
 [3.99219562e-01 6.00780438e-01]
 [8.00956339e-01 1.99043661e-01]
 [9.87368777e-01 1.26312234e-02]
 [2.59388962e-01 7.40611038e-01]
 [8.12393242e-01 1.87606758e-01]
 [7.86958005e-02 9.21304199e-01]
 [8.55845523e-01 1.44154477e-01]
 [8.97164539e-01 1.02835461e-01]
 [8.09660019e-01 1.90339981e-01]
 [2.09953393e-02 9.79004661e-01]
 [9.27877047e-01 7.21229534e-02]
 [1.74728499e-01 8.25271501e-01]
 [1.36623908e-02 9.86337609e-01]
 [9.72798872e-02 9.02720113e-01]
 [1.85955225e-03 9.98140448e-01]
 [9.01429628e-01 9.85703721e-02]
 [3.004252

In [12]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
score=accuracy_score(y_test,y_pred)
cm = confusion_matrix(y_test,y_pred)
cr = classification_report(y_test,y_pred)
print(score)
print(cm)
print(cr)

0.895
[[81 12]
 [ 9 98]]
              precision    recall  f1-score   support

           0       0.90      0.87      0.89        93
           1       0.89      0.92      0.90       107

    accuracy                           0.90       200
   macro avg       0.90      0.89      0.89       200
weighted avg       0.90      0.90      0.89       200

